version: '3.1'

services:
  app:
    build: .
    restart: always
    command: gunicorn --bind 0.0.0.0:5005 app:app
    ports:
      - "5005:5005"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
